version: "3.9"
services:

  redis:
    image: 192.168.11.136:5000/redis:alpine

  db:
    image: 192.168.11.136:5000/postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data

  vote:
    image:  192.168.11.136:5000/dockersamples/examplevotingapp_vote
    ports:
      - 5100:80
    deploy:
      replicas: 1
      
  result:
    image:  192.168.11.136:5000/dockersamples/examplevotingapp_result
    ports:
      - 5001:80

  worker:
  image:  192.168.11.136:5000/dockersamples/examplevotingapp_worker
    deploy:
      replicas: 1

volumes:
  db-data: